### PR TITLE
Added support for NTLM/Windows auth using standard "DOMAIN\user" input convention

### PR DESCRIPTION
**Pull request by jshca**
Thought this might be useful...

### CODE REVIEW

**Comment by reverentgeek** [comment]
Wow, that looks awesome :) I'll take a closer look soon.

Thanks!

**Comment by jshca** [comment]
So... I hastily pushed that last commit.  This second commit should fix it.

**Comment by reverentgeek** [comment]
Have you tested this in your environment? I've tested your pull request and got it to work with a VM using `servername\username`, but it's not configured as a domain. 

Also, there's another TFS connection that happens in `TfsConnection.cs` that is used by the UI configuration utility. I assume this must be working with the domain scenario, if you're able to connect to your instance of TFS and configure the Integration Service.

**Comment by jshca** [comment]
David,

Yes, I have it running in “production” right now.  (I’m still getting it set up against the boards/work items we’re using)  But it is working so far.  I did make a stupid mistake in the first commit on the pull request.  I had been testing a couple of builds and committed code for a build that hadn’t been fully tested.  A subsequent commit fixed it, so make sure you picked that up.  Honestly, I don’t know much about NTLM *or* C#/.NET, so I was just poking around at it.  But I happened to discover that the NetworkCredentials(?) class had another constructor that allowed a Domain parameter and I thought I’d try it.  It works against our domain, but I’m not sure how it would behave against a standalone server.

(Also, this patch was quick-and-dirty, so I’m not sure it’s really good style.  You may want to find a more elegant way to pass that optional Domain param.)

Anyway, let me know if I can help with anything else…

--
Jon

[cid:image001.jpg@01D13CA9.4476F000]

Jon Sharp
Consulting Application Engineer
ERP Systems

Jon.Sharp@HCAHealthcare.com<mailto:Jon.Sharp@HCAHealthcare.com>
o: (615)236-3695
730 Cool Springs Blvd. Franklin, TN 37067
healthcareinspired.com
[social1]<https://www.linkedin.com/company/hca-it&s?trk=company_name>   [social2] <http://twitter.com/HCA_IT>   [social8] <http://www.facebook.com/hcaits>

**Comment by reverentgeek** [comment]
It seems to work fine with standalone server, so I'm declaring it a success :+1: 

I'll get this merged and a build published out on our downloads page. Thanks again!

**Pull request merged**
